[package]
name = "tmux_abbreviate_path"
version = "0.1.0"
authors = ["Stanislav Baiduzhyi <baiduzhyi.devel@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.1"

[[bin]]
name = "tmux-abbreviate-path"
path = "tmux-abbreviate-path.rs"
